{"Nível": 0, "Disciplina": "Matemática Básica", "Video": "", "Resumo": ""}

disciplinas = {
    "Matemática Básica": {
        "Operações Fundamentais": {"Nível": 0, "Disciplina": "Matemática Básica", "Video": "https://www.youtube.com/watch?v=h3sFlP8Rmqc", "Resumo": "", "Requisitos": []},
        "Expressões numéricas": {"Nível": 0, "Disciplina": "Matemática Básica", "Video": "https://www.youtube.com/watch?v=fG3tzCME95Y", "Resumo": "", "Requisitos": []},
        "Frações": {"Nível": 0, "Disciplina": "Matemática Básica", "Video": "https://www.youtube.com/watch?v=baJ2jp3_ZHE", "Resumo": "", "Requisitos": []},
        "Operações com Frações": {"Nível": 0, "Disciplina": "Matemática Básica", "Video": "https://youtu.be/dZfWflhf_IU", "Resumo": "", "Requisitos": []},
        "Dízimas periódicas": {"Nível": 0, "Disciplina": "Matemática Básica", "Video": "https://youtu.be/7O7KQxJGpx4", "Resumo": "", "Requisitos": []},
        "Sistemas de Numeração e Sistema Métricos": {"Nível": 0, "Disciplina": "Matemática Básica", "Video": "https://youtu.be/VBUD3CzsEH0", "Resumo": "", "Requisitos": []},
        "Raciocínio lógico": {"Nível": 0, "Disciplina": "Matemática Básica", "Video": "https://youtu.be/PltqUuwR9ec", "Resumo": "", "Requisitos": []},
        "Potenciação": {"Nível": 0, "Disciplina": "Matemática Básica", "Video": "https://youtu.be/qMY0WODedII", "Resumo": "", "Requisitos": []},
        "Notação científica": {"Nível": 0, "Disciplina": "Matemática Básica", "Video": "https://youtu.be/1JBkreMDKSI", "Resumo": "", "Requisitos": []},
        "Radiciação": {"Nível": 0, "Disciplina": "Matemática Básica", "Video": "https://youtu.be/4X8ct8KLHW4", "Resumo": "", "Requisitos": []},
        "Racionalização de denominadores": {"Nível": 0, "Disciplina": "Matemática Básica", "Video": "https://youtu.be/8wIpnNa8Yv8", "Resumo": "", "Requisitos": []},
        "Produtos notáveis": {"Nível": 0, "Disciplina": "Matemática Básica", "Video": "https://youtu.be/ssPi9-lLMIY", "Resumo": "", "Requisitos": []},
        "Fatoração": {"Nível": 0, "Disciplina": "Matemática Básica", "Video": "https://youtu.be/ZUtMAmCkzNs", "Resumo": "", "Requisitos": []},
        "Equações do primeiro grau": {"Nível": 1, "Disciplina": "Matemática Básica", "Video": "https://youtu.be/ds4GHCU42wM", "Resumo": "", "Requisitos": ["Operações Fundamentais", "Expressões numéricas", "Radiciação", "Potenciação"]},
        "Sistemas do primeiro grau": {"Nível": 1, "Disciplina": "Matemática Básica", "Video": "https://youtu.be/iaPQ2U8o31M", "Resumo": "", "Requisitos": ["Equações do primeiro grau"]},
        "Equações do segundo grau": {"Nível": 1, "Disciplina": "Matemática Básica", "Video": "https://youtu.be/Xv2QrQK9I7E", "Resumo": "", "Requisitos": []},
        "Critérios de divisibilidade": {"Nível": 0, "Disciplina": "Matemática Básica", "Video": "https://youtu.be/RAXp2qjhA1M", "Resumo": "", "Requisitos": []},
        "Números primos": {"Nível": 0, "Disciplina": "Matemática Básica", "Video": "https://youtu.be/vP0SquC1gSU", "Resumo": "", "Requisitos": []},
        "MMC": {"Nível": 0, "Disciplina": "Matemática Básica", "Video": "https://youtu.be/PmlNQeBfp7I", "Resumo": "", "Requisitos": []},
        "MDC": {"Nível": 0, "Disciplina": "Matemática Básica", "Video": "https://youtu.be/MK4cSSdNTHo", "Resumo": "", "Requisitos": []},
        "Razão e proporção": {"Nível": 0, "Disciplina": "Matemática Básica", "Video": "https://youtu.be/bM9v6Bgp8qM", "Resumo": "", "Requisitos": []},
        "Regras de 3 Simples": {"Nível": 0, "Disciplina": "Matemática Básica", "Video": "https://youtu.be/mnle8NcUYkQ", "Resumo": "", "Requisitos": []},
        "Regras de 3 Composta": {"Nível": 0, "Disciplina": "Matemática Básica", "Video": "https://youtu.be/vKU-85u6yJw", "Resumo": "", "Requisitos": ["Regra de 3 Simples"]},
        "Escalas": {"Nível": 0, "Disciplina": "Matemática Básica", "Video": "https://youtu.be/xcgHnXkiA9k", "Resumo": "", "Requisitos": []},
        "Porcentagem": {"Nível": 0, "Disciplina": "Matemática Básica", "Video": "https://youtu.be/CERiIwParX4", "Resumo": "", "Requisitos": []},
        "Lucro e Juros simples": {"Nível": 0, "Disciplina": "Matemática Básica", "Video": "https://youtu.be/N27xZJj1m-4", "Resumo": "", "Requisitos": []},
        "Juros compostos": {"Nível": 0, "Disciplina": "Matemática Básica", "Video": "https://youtu.be/790S9GR5bWU", "Resumo": "", "Requisitos": []}
    },
    "Álgebra": {
        "Teoria dos conjuntos": {"Nível": 0, "Disciplina": "Matemática", "Video": "https://www.youtube.com/watch?v=0aUEDxYjZg8&list=PLTPg64KdGgYgTXWPsURDnPBd7GUwPVBLx", "Resumo": "", "Requisitos": []},
        "Conjuntos numéricos": {"Nível": 0, "Disciplina": "Matemática", "Video": "https://www.youtube.com/watch?v=s5Xv1SIQnQE", "Resumo": "", "Requisitos": []},
        "Intervalos reais": {"Nível": 1, "Disciplina": "Matemática", "Video": "https://youtu.be/osSJGcW7vsc", "Resumo": "", "Requisitos": []},
        "Progressão aritmética (PA)": {"Nível": 2, "Disciplina": "Matemática", "Video": "https://www.youtube.com/watch?v=QE3GieQD-Ps&list=PLEfwqyY2ox85NtaWwua8KHQYEx5I7qe3E", "Resumo": "", "Requisitos": []},
        "Progressão geométrica (PG)": {"Nível": 2, "Disciplina": "Matemática", "Video": "https://www.youtube.com/watch?v=lWqOrQ3GZC0&list=PLEfwqyY2ox85NtaWwua8KHQYEx5I7qe3E&index=6", "Resumo": "", "Requisitos": []},
        "Teoria geral de funções": {"Nível": 2, "Disciplina": "Matemática", "Video": "https://www.youtube.com/watch?v=L4iX1MZXbVs&list=PLEfwqyY2ox84KtQdRncCBovhDyUGz70TW", "Resumo": "", "Requisitos": ["Teoria dos conjuntos", "Conjuntos numéricos", "Equações do primeiro grau"]},
        "Função afim": {"Nível": 1, "Disciplina": "Matemática", "Video": "https://www.youtube.com/watch?v=hdMFlAv5GkU&list=PLTPg64KdGgYjMtxN9pJGBaenIRwNX1EtI", "Resumo": "", "Requisitos": ["Teoria geral de funções"]},
        "Função do segundo grau": {"Nível": 2, "Disciplina": "Matemática", "Video": "https://www.youtube.com/watch?v=ZpW9Xb5iyt4", "Resumo": "", "Requisitos": ["Equações do segundo grau"]},
        "Função composta": {"Nível": 3, "Disciplina": "Matemática", "Video": "https://youtu.be/EBRXQpXbXio", "Resumo": "", "Requisitos": ["Teoria geral de funções"]},
        "Função inversa": {"Nível": 3, "Disciplina": "Matemática", "Video": "https://youtu.be/D4jnxW3iypQ", "Resumo": "", "Requisitos": ["Teoria geral de funções"]},
        "Função exponencial": {"Nível": 3, "Disciplina": "Matemática", "Video": "https://www.youtube.com/watch?v=n5NRv2cWQIg&list=PLTPg64KdGgYhllRJbaGMQGRa-3-3RNGzb", "Resumo": "", "Requisitos": ["Potenciação"]},
        "Logaritmos": {"Nível": 4, "Disciplina": "Matemática", "Video": "https://www.youtube.com/watch?v=xpUxOm7M76w&list=PLGyv8aUrOlzA9SnHx_PAGmbvfsCcGslnt", "Resumo": "", "Requisitos": []},
        "Função logarítmica": {"Nível": 4, "Disciplina": "Matemática", "Video": "https://www.youtube.com/watch?v=P8uxcolt8OQ", "Resumo": "", "Requisitos": []},
        "Função modular": {"Nível": 3, "Disciplina": "Matemática", "Video": "https://youtu.be/iT0KSy08itc?list=PLEfwqyY2ox85oONCxkeT4DWj3C1PU-9Ec", "Resumo": "", "Requisitos": []},
        "Funções trigonométricas": {"Nível": 5, "Disciplina": "Matemática", "Video": "https://youtu.be/O1JCMiXfWY4?list=PLTLS-I2PnyJi4Biu481NVdOL0GhvY8J0d", "Resumo": "", "Requisitos": []},
        "Matriz e Determinante": {"Nível": 6, "Disciplina": "Matemática", "Video": "https://youtu.be/lZ9onrdpusA?list=PLEfwqyY2ox868TPa8vjL-QPfQlmtqRGa5", "Resumo": "", "Requisitos": ["Sistemas do primeiro grau"]},
    },
    "Geometria": {
        "Ângulos": {"Nível": 1, "Disciplina": "Geometria", "Video": "https://youtu.be/fLJtL0_9UEs", "Resumo": "", "Requisitos": []},
        "Triângulos": {"Nível": 1, "Disciplina": "Geometria", "Video": "https://youtu.be/OA4qRsc7nSA", "Resumo": "", "Requisitos": []},
        "Tipos de triângulos": {"Nível": 1, "Disciplina": "Geometria", "Video": "Triângulo", "Resumo": "", "Requisitos": ["Triângulos"]},
        "Semelhança de triângulos": {"Nível": 2, "Disciplina": "Geometria", "Video": "", "Resumo": "", "Requisitos": []},
        "Paralelismo Entre Retas no Plano": {"Nível": 1, "Disciplina": "Geometria", "Video": "", "Resumo": "", "Requisitos": []},
        "Teorema de Tales": {"Nível": 2, "Disciplina": "Geometria", "Video": "", "Resumo": "", "Requisitos": []},
        "Triângulo retângulo: relações métricas": {"Nível": 2, "Disciplina": "Geometria", "Video": "", "Resumo": "", "Requisitos": []},
        "Triângulo retângulo: relações trigonométricas": {"Nível": 3, "Disciplina": "Geometria", "Video": "", "Resumo": "", "Requisitos": []},
        "Lei dos senos e dos cossenos": {"Nível": 4, "Disciplina": "Geometria", "Video": "", "Resumo": "", "Requisitos": []},
        "Polígonos": {"Nível": 2, "Disciplina": "Geometria", "Video": "", "Resumo": "", "Requisitos": []},
        "Quadriláteros": {"Nível": 1, "Disciplina": "Geometria", "Video": "", "Resumo": "", "Requisitos": []},
        "Áreas de figuras planas": {"Nível": 1, "Disciplina": "Geometria", "Video": "Triângulo", "Resumo": "", "Requisitos": ["Triângulos", "Quadriláteros e Hexágonos", "Polígonos"]},
        "Circunferência e Círculo": {"Nível": 2, "Disciplina": "Geometria", "Video": "", "Resumo": "", "Requisitos": []},
        "Geometria de posição: Posições relativas e Projeção ortogonal": {"Nível": 4, "Disciplina": "Geometria", "Video": "", "Resumo": "", "Requisitos": []},
        "Poliedros": {"Nível": 4, "Disciplina": "Geometria", "Video": "", "Resumo": "", "Requisitos": []},
        "Prismas": {"Nível": 3, "Disciplina": "Geometria", "Video": "", "Resumo": "", "Requisitos": []},
        "Cilindros": {"Nível": 3, "Disciplina": "Geometria", "Video": "", "Resumo": "", "Requisitos": []},
        "Pirâmides e Troncos de pirâmides": {"Nível": 4, "Disciplina": "Geometria", "Video": "", "Resumo": "", "Requisitos": []},
        "Cones e Troncos de cones": {"Nível": 3, "Disciplina": "Geometria", "Video": "", "Resumo": "", "Requisitos": []},
        "Esferas": {"Nível": 4, "Disciplina": "Geometria", "Video": "", "Resumo": "", "Requisitos": []},
        "Sólidos inscritos": {"Nível": 3, "Disciplina": "Geometria", "Video": "", "Resumo": "", "Requisitos": []},
        "Estudo do ponto": {"Nível": 2, "Disciplina": "Geometria", "Video": "", "Resumo": "", "Requisitos": []},
        "Estudo da reta": {"Nível": 3, "Disciplina": "Geometria", "Video": "", "Resumo": "", "Requisitos": []},
        "Estudo da circunferência": {"Nível": 4, "Disciplina": "Geometria", "Video": "", "Resumo": "", "Requisitos": []},
    },
    "Estatística": {
        "Princípio Fundamental da Contagem (PFC)": {"Nível": 1, "Disciplina": "Estatística", "Video": "", "Resumo": "", "Requisitos": []},
        "Fatorial": {"Nível": 1, "Disciplina": "Estatística", "Video": "", "Resumo": "", "Requisitos": []},
        "Arranjo": {"Nível": 2, "Disciplina": "Estatística", "Video": "", "Resumo": "", "Requisitos": []},
        "Permutação simples e Permutação circular": {"Nível": 3, "Disciplina": "Estatística", "Video": "", "Resumo": "", "Requisitos": []},
        "Combinação": {"Nível": 3, "Disciplina": "Estatística", "Video": "", "Resumo": "", "Requisitos": []},
        "Estatística: Visão geral, Organização e Representação de dados": {"Nível": 2, "Disciplina": "Estatística", "Video": "", "Resumo": "", "Requisitos": []},
        "Estatística: Médias, Medidas de tendência central e de dispersão": {"Nível": 2, "Disciplina": "Estatística", "Video": "", "Resumo": "", "Requisitos": []},
        "Interpretação de gráficos": {"Nível": 3, "Disciplina": "Estatística", "Video": "", "Resumo": "", "Requisitos": []},
        "Probabilidade: Visão geral": {"Nível": 3, "Disciplina": "Estatística", "Video": "", "Resumo": "", "Requisitos": []},
        "Probabilidade da união de eventos": {"Nível": 3, "Disciplina": "Estatística", "Video": "", "Resumo": "", "Requisitos": []},
        "Probabilidade de eventos simultâneos": {"Nível": 3, "Disciplina": "Estatística", "Video": "", "Resumo": "", "Requisitos": []},
        "Probabilidade condicional": {"Nível": 4, "Disciplina": "Estatística", "Video": "", "Resumo": "", "Requisitos": []},
    },
    "Geral": {
        "Interpretação de Gráficos": {"Nível": 1, "Disciplina": "Geral", "Video": "", "Resumo": "", "Requisitos": []},
        "Interpretação de Problemas": {"Nível": 1, "Disciplina": "Geral", "Video": "", "Resumo": "", "Requisitos": []},
        
    }
}