import json

from Database import Database
from Estudante import Estudante

import validate as pv

with open('alunos_atualizados.json', 'r', encoding="utf-8") as arquivo:
    dados = json.load(arquivo)

def recadastrar(dados, database):
    for i, data in enumerate(dados.values()):
        nome = pv.validar_name(data["nome"])
        cpf = pv.validar_cpf(data["cpf"])
        celular = pv.validar_celular(data["telefone"])
        email = pv.validar_email(data["email"])
        cep = pv.validar_cep(data["cep"])
        numero = data["num_casa"]
        periodo = data["periodo"]
        curso = data["curso"]
        ano = data["ano"]
        nascimento = data["nascimento"]
        etnia = data["etnia"]
        genero = data["genero"]

        if celular == False:
            celular = 11111111111

        if email == False:
            email = "provisorio@gmail.com"
        
        if cep == False:
            cep = "13060492"

        student = Estudante(nome, data["cpf"], celular, email, cep, numero, periodo, curso, ano, nascimento, etnia, genero)
        database.insertStudent(student.__dict__)
        print(f"Adicionado - {nome}")

def atualizarEstudantes():

    # Iniciando o banco de dados
    database = Database()

    for i, data in enumerate(dados.values()):
        try:
            database.updateStudent(data["cpf"], data["Simulados"])
        except:
            database.updateStudent(data["cpf"], {"Colmeias_Inicial": None, "Unicamp_00001": None})
            
def ajustarResposta(resposta_str):
    dict_res = {}
    
    for i in range(0, len(resposta_str)):
        dict_res[i + 1] = resposta_str[i]
    
    print(dict_res)

database = Database()
# recadastrar(dados, database)
# atualizarEstudantes()

# lista = [["42375356810", "CBCDAEECECDEDEBBEBBEBBCACBBEBABCBACBBEDCDDAAACCCCCEFDEAEDABBDACBEBCABADDABBDBBAAADAEADCDAE"],
# ["45720677836", "CBCBBECBDCDEEABEEDBCBABDAEBCBDDCEBDDCCDADDADBCECBADFDBDECEBEDBCBABDCDCCDBEBDAAAEBAABBDCCCB"],
# ["47180957860", "CCCBDACBAACDECCAEEBEBDDBABDACDDDACDEACECBCABACEBEDAADCDDCCBBCDCBEBCADACDADADBAECEDAAEDACAC"],
# ["50872930858", "BCEAABDBEBACBEDBEEBEBDBACDAECEAABDCBACEDBBADACBDEDBCEBCBADADEBCADBCEECAEBADDAABEEDABDCACBA"],
# ["49075533828", "EECCCDCBECEDEEAEEBBEBCCBABDACABBADADBCEEBCCDDAEBCDACCCDECEBEDECEDBDDCBECDDDDAABCADAAEDDCAC"],
# ["48302440892", "CBCEAAABEBEEAEABEEAEDCEACCBDCDCCBDCDAADAADBEABBBBAEBECADCDCBCDCBADCDDBABAEDEAAACCDAAEAADEE"],
# ["54575479810", "DEADAAECBCADBECDEEBEBCEBBCEBEBBBBACECBDADDBDAEDDBADCDCDDBEEBADCBABCBBBABBCCABABCDEAACEDCAA"],
# ["44977192869", "DDCCBBDCCBDECCBBEABDBCDBCCCBBDBAADDADADDCDBCDCECDDBFDDDDCDBEEDCBCCDAEDBDBCADECBCBEAECCDAED"],
# ["55386818821", "CAEBABEDEECEDEAADBADBAEBCDBEDEEBBACCCDBAADABCAEBBEBFDCDDDECBFBCCABCCEECBECDDAEEECDDCCDCBCC"],
# ["21502798867", "DBCCEBDADACCBEABEEBEBCEBCADBCDCDDCCCCABBEDADAAAABAEFDEEDBCEBDBCBEBDCEDBAAEEDADAABDAAEEADCB"],
# ["46554975802", "ABDACBABDAADBADCADCCBBDAAAAABDBCEDCBBEBDACADADBDEBEFACEDCACBEDCEADCAEDDCCBCACEBCDDAACCDCEE"],
# ["48683910890", "DABBBDEABBBDEEBBEBEADBCACCCABBCCBBDBCCBBDDABAEFCDACFCADDCCBBADCBABCDABACAEABBCEDFAAABCACEC"],
# ["42388999898", "DBCDECAECACAEEBBEBEEBADCCACBDEDDABCEACDCDCABAEBDABAFDBCDCDBBADCBAEBBDECDAEBDAABEDDAEBBCCBC"],
# ["42457274893", "BCADADAEECADADDBEABCBBCACDEBCADCEBEDBDBACBCEDBCDAADFEADDACCADDCBADAAEBCDDADDAAACADAAADBCAC"],
# ["54654541802", "BCDCEBDCEBEADEAAEEBABABABCCBBBBAACCCCDBCDCDCACDBBCDFEDDECDCBDCCBABDBDBCCDEDAAAEBACAAABAAAE"],
# ["56628057844", "ABADADACBAAEEDAEEBCBBCDACADCDACBADCDBEDEBABCDAAEBAEFDCDDBCBBEDCBADDCEABDAEEBBABCCADEEBAEAB"],
# ["02805184556", "CBAADDEBECEEADDCEBEADCBEACACBCAABDEDCCDCCABBBCAEBEDCDEEDDDBECDCCCBCDABABBECBABECADAACBCBAC"],
# ["54414605806", "ABADAECACCCEEEABEEBABBDDECCBDBDECADACDDDDDDDADAABDDCDEDDDCBCCBCACECBDACDDEBBECECEDAEECDBDD"],
# ["56033765893", "FACDCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDBADDDDADBBDDCEABCCDCBBDECDBCFABCAABDCCAC"],
# ["52134170867", "CCCCABCBCCBECDBCEBBDBCDBCCBDADBCADCBCDBAEABBDECDCABDDDDDCCBBDDCBABDBDECDBBADCFDCADAABDCCEE"],
# ["43491864844", "DECDEBABCCEDEACBEDAABCDBEAEBDABDEABECCEBABACDBABEADFCDDDEDBBDDCDABDAABACAEBBCABCADBDACADAC"],
# ["56055936844", "BBADCEACEAAEEDBCECAADBBECCCBDEBCCACEDBDBDBADAACBBAEBEEDDEEECECCAEECCEBBDEAEAADEDCDAAADBAEC"],
# ["41021351890", "EBEDDDCABAECCECCBEDBBBCCCCCCBBCCACCCEAEDEDDDEEEDAEEBECDAEDDDEBAAACCCDDADDDDDAADAAAEADDAEED"],
# ["47462189860", "EECBEECBEAAABEABCEBEBCDACBDDDDDDDDDDCBDDADADDEDDEABBDCDDCCBBBACBABCCDBADEEDEAAACADAAEDCCAA"],
# ["51460191854", "DACBEBDCEABAADBBEEADBEDCCCCBCABBADDDCBDDECAABEDCCADFDCDDBDDEDDBEACCDACCBDCCBAAACBDDCAACBEC"],
# ["42295436809", "DDCBDBBCBAAEEDCDEABCDDBCBCDBBDBEAABBCCDAABEBAABADADDDBDDCCBDDEBBDEAEEABEBDACCCAAEDAABEAABB"],
# ["73777533862", "ECEDADACCACDEDBDEEBABBDADEEBBDECABDDCDEDBDEBECCBBCBFECEDCCCBDBCBEDCADCADBADADAECADABBDEBAC"],
# ["56899563843", "EBCDEBDAEAADDDBBEBBADDBBBAECBADDABDDBBBCEDDBACBDECCFECDBABFAEDCBEACAAECCADDBBCADADAEBBDDCC"],
# ["13780172852", "CCCDADBABACDDCBDEBBCDDDDECEABACEEDCDCDCADBCACEBDCDEFDBDDCEEDCBCDAEDEEDEBCEADADACDDDBACCACC"],
# ["49559210866", "DBACCECBABDAEDDAECCABACABCADDACCBBCDCCBBECCBBEABCBDDBCDDBEBBDDCBABCACEDCAECBAAAEAEAAAEACAA"],
# ["49095750817", "DECBEABBECAEBECBEEBABDDADCABCDDEABCECBDADDDCAEBCBABFDCDDCCBBDDCBABCCACEEEBBDADACBDAAEDDCAE"],
# ["46463590819", "DECCAACBDEEDBDBAEEBDBAECBCCAEBDBADECACADBCBEBAABBDDEECDEBCBEDDCBABCCEDAEAEBCAABBEDDAEDDCCC"],
# ["51856588866", "ECBECBAADECAADCEDABEBCBABAABBCACAACAEAABACDDACBCCBAFEEEDCADBEBABAEAABADACBAAACEADFBDDCECAB"],
# ["51634540808", "ACACEBAECDEDDEBEEBBCDDCBACDCBADCACEDBDEBABCAAEABAAEFEAEDBCBADACBDCCDBEADDCABACACADAAEDADEB"],
# ["49262191820", "FBBBABCBDDAEEDBBEABBBDEADDDDCDBCCDDBCDDAEDCBABCBBADDDBDDBCBBBDCBCDCCECBBADEDBAACADAAEEABEA"],
# ["08865181800", "CECEBADECBEDCBBBEABDBECADBBAEDDBBACABDEACAAEAECDAEEDDADDDEEBADCBEECDDEBDAAADAAECBDAEEDCCEC"],
# ["42198503840", "ABACCCCBECDAEEEAEAACBBACACCCBBAEDCDEBDDAABDCACCDCADCEDDDEBBBEDCBABCDDCAAEEBAAABEADAAEDCDEC"],
# ["12054987883", "DBBCEBEDCAAEDECDEBBADBDDCBEBBACDBACBBDCAECABABBDBBDFDCADDDCBDACBEBDCADBDDEDEAEACCDADBEDDAD"],
# ["51788313810", "DAAADBCCEDCCEEDBEEBBDDCADCDBBCECBADEADBCDADDAECCCAAFDDDDCCBBCACBABCCACCDAEEDACACDDAAADCEAA"],
# ["48898566840", "DBEBDDACBBCEADCBECCABDDEBEDBDBBAECCDCAEBDDADBABEBCBEDBDDBDEBCCCAEBEBADEBAACAAABBEDCABDCDCA"],
# ["50943012848", "DCBCABDDECAEACDBEEBCDEDABABABDBAAEBCCEDBDABBACBCBDADAACDBDCDCBCDADACCECCDADCACADAEABDCABCD"],
# ["12031760823", "ABBCCECADECEBEEBEBBABABADCBDCABCACBCDDDDAAABACCDCADDDCDDCCDBCDCAADDCBCCDABEBAAAADDAAEEDCAA"],
# ["53715639890", "DBDBECECCABEDCADEABDDBDADBEBBBDDADCACBDADCDBACEBACBFCCCBBDBEAECBADCCEEBCAEBEDCAACDABCDEEEA"],
# ["48885597831", "ABEDDCBDBBCEEEBBEEBDDDAEACCBBDBCAAECBEAADBDEAACCDBCFEAADADCBEDCBABCCDBDDDEBAAAEABAAABECDCA"],
# ["53122536854", "CDBCECCBDBAEDDCAAEBDDDCAAEDEBDDEAECBCCDAABDBABBADABFEECDCEBBCDCBCEACAEAAADEEAADEBDAAECBBDC"],
# ["38694138832", "EBDDCAABDDAEDDCEEEBBBDABCCCCBEDBABCDDADDDDCBBBDBCEEDEBDDDCBAAACCAECAEEECBABDEAABDEAACCBEEA"]]

# for item in lista:
#     try:
#         database.insertSimuladoStudent(item[0], "USP_00001", item[1])
#     except:
#         print(item[0])
