simulados = {
    "Colmeias_Inicial": {
        "Gabarito": {
            "1": {"Resposta": "D", "Disciplina": "Português", "Conteudo": ["Funções da Linguagem", "Morfologia"]},
            "2": {"Resposta": "A", "Disciplina": "Português", "Conteudo": ["Morfologia", "Concordância Verbal"]},
            "3": {"Resposta": "A", "Disciplina": "Português", "Conteudo": ["Funções da Linguagem", "Variação Linguística"]},
            "4": {"Resposta": "C", "Disciplina": "Português", "Conteudo": ["Figuras de Linguagem", "Morfologia", "Verbos"]},
            "5": {"Resposta": "E", "Disciplina": "Português", "Conteudo": ["Morfologia", "Substantivo, Adjetivo, Numeral e Artigo"]},
            "6": {"Resposta": "D", "Disciplina": "Física", "Conteudo": ["Movimento uniforme", "Matemática Básica", "Porcentagem"]},
            "7": {"Resposta": "B", "Disciplina": "Física", "Conteudo": ["Ondulatória", "Movimento Uniforme"]},
            "8": {"Resposta": "E", "Disciplina": "Física", "Conteudo": ["Eletricidade", "Gráficos"]},
            "9": {"Resposta": "E", "Disciplina": "Matemática", "Conteudo": ["Geometria Espacial", "Volume"]},
            "10": {"Resposta": "A", "Disciplina": "Matemática", "Conteudo": ["Medidas de Centralidade e Dispersão", "Tabela"]},
            "11": {"Resposta": "B", "Disciplina": "Matemática", "Conteudo": ["Matemática Básica", "Adição e Subtração", "Potenciação", "Radiciação"]},
            "12": {"Resposta": "B", "Disciplina": "Matemática", "Conteudo": ["Porcentagem", "Matemática Financeira"]},
            "13": {"Resposta": "C", "Disciplina": "Matemática", "Conteudo": ["Função do 1º Grau", "Gráficos", "Tabela"]},
            "14": {"Resposta": "B", "Disciplina": "Geografia", "Conteudo": ["Conceitos em Geografia e Introdução à Demografia", "Migrações"]},
            "15": {"Resposta": "E", "Disciplina": "Geografia", "Conteudo": ["Industrialização Brasileira"]},
            "16": {"Resposta": "C", "Disciplina": "Geografia", "Conteudo": ["Energia"]},
            "17": {"Resposta": "C", "Disciplina": "História", "Conteudo": ["Governo Vargas"]},
            "18": {"Resposta": "B", "Disciplina": "História", "Conteudo": ["Idade Moderna"]},
            "19": {"Resposta": "B", "Disciplina": "História", "Conteudo": ["Segunda Guerra Mundial", "Autoritarismo"]},
            "20": {"Resposta": "A", "Disciplina": "Química", "Conteudo": ["Química Orgânica"]},
            "21": {"Resposta": "A", "Disciplina": "Química", "Conteudo": ["Química Orgânica", "Classificação e Hibridização do Carbono", "Classificação de Cadeias Carbônicas"]},
            "22": {"Resposta": "D", "Disciplina": "Química", "Conteudo": ["Equilíbrio Iônico"]},
            "23": {"Resposta": "D", "Disciplina": "Biologia", "Conteudo": ["Biociclos e Biomas", "Ecologia"]},
            "24": {"Resposta": "C", "Disciplina": "Biologia", "Conteudo": ["Saúde"]},
            "25": {"Resposta": "D", "Disciplina": "Biologia", "Conteudo": ["Citologia"]}
        },
        "Gabaritos_Alunos": {
            "-NrBuWfRVnTXIqUkVD7j": "DADDCCBBDCBCBBECAAAABACCB",
            "-NpPiXstkQhpVUwXk02x": "BCCBBADCDEBCBCCADBBCDCBCE",
            "-NsZ2TUAS2FTuOMqw89H": "DADCBDBEEABBCBECABBAABCCD",
            "-NruBjdIiUYUWW5ABguL": "DACACBCDEDBBCCEAAEBABCADD",
            "-NsmN1MHlB1w7GpLDQ-U": "DBCCBCDCDBBABDACEDDABCDDD",
            "-Ns_3c3m8k479xbwz92A": "DAECBECEAABACAECCBDBEBCCD",
            "-Ns8MzOoubwwCWpPoAlD": "DDEDDCEECBBACBECBDBAADDDA",
            "-NrerG7lApyhE37b23Bq": "DAACBBAEBABAEDCAEECACACDD",
            "-NrtvOAF3cJtvYFfsGzC": "DAADDECDBABDCCAECADCBEACA",
            "-NsOPDxVBhcxUnh9B-sR": "DCCCEBECABBCCABCDBBACECDD",
            "-NtX17mTXwY95dYVHZ8U": "BAEBDCBEEADDCDECABBDBCDDE",
            "-NpWcFSP1y7uAO3gQO7U": "DABBCBDEEABBAAECDBBAACCCD",
            "-Ns8sq9Y9TPEtJqooBS6": "EECCABBECBBADACDECAAEBBAD",
            "-NsnzcJn11H_CFbx-EmB": "DDACEEDCCABBEAECBBBABBDDD",
            "-Ns8WSUNgdvUFcds4Z54": "DACCECCEBEBADABCEBBAAADED",
            "-Ns9eSl96YVtghzvsAwD": "ABEDBCCDADDACABCBEBADBCDD",
            "-NsY6FAnM58MtuZbY5hu": "DABDBCCCDEBAAABCCBCBBAEDC",
            "-Nq2cAnk4ZFdNbiTXe79": "DABBACDDBBBAEDECDBBAADCCD",
            "-NswaxcU1dM9Mi3FKZHK": "DABDCCBECEAECACDABDCBADCD",
            "-NsmHzt00jL-Jlmah01W": "DACDEBDCBDBBDCABEEDBFFFFF",
            "-Nt1TjePJxmLayK2xFmX": "DBADECBCDEADADCCBBDAAECCA",
            "-NpWLdJkscUyYXH143pn": "DBCCEEDEBABACEBCBECAAADDB",
            "-NpKGYe49ixF4BXth9dG": "DEDDCCAEBABDCABBCBCABCCCA",
            "-NrpsYAA3XldX1MQDHpT": "DCCADADEDABACAACBBAACBDED",
            "-NsmJ-pYkvkhcTRCTkTQ": "BCCBFCFCCFBDFDECCFFFFFFFF",
            "-Npu365YyDNGcTeR7fh-": "DECCEADECEBDACECABBABAACD",
            "-NpzrRxO6aaaWyn-osTm": "DCBDECAEDDBAAAECCDCABDDCC",
            "-NsUCHyhCYuW4frHavih": "DCDCEACEDBBBEBECDBBACCDEA",
            "-NpPaHEgFS-MtM6eoWrD": "DCACCABECBBACCECEBBACDDED",
            "-NpM60kZr97ETBSjT3em": "DBDCEDBEAABBCBBCEBBAADDDD",
            "-NsT3untPBVbLsxZMVHS": "DCADCEAECBBAABBCBBAAABDCD",
            "-Ns8r6VDAMD6IP95qS-s": "DDDCCCDEBCBAAAECCBBBEDDDA",
            "-NsTzS33TAhT_zgyRkN8": "DEDBDBDCBDBAAACCBBAAADCED",
            "-NpW7mAoNirVgqwj_OTh": "DACDECBCDCBCABBEEBBADAEDA",
            "-NsTs2dq4GFs_VpMQOij": "DAEBDCDECDBDAAECABCAADCED",
            "-NpUjYTOwJvPPxq_5tYE": "DADDDCCCBEBDCABCADCABCDCD",
            "-NsZ7IEQYxO9-cGpPG8f": "DEDDBEFBCEBDBABDDBBAACDCD",
            "-Nr0WkuCMbD90mu6mY_T": "DDBDCACABCBBABBCCDBACADDA",
            "-Nrq6lwAfkLPXeOQxPfz": "DCCDDDCEDABECAECEDCABADDD",
            "-Nr7ChLzI5WL-DXmRmvB": "DCBCEDEEDABBDDECABBAABDCD",   
            "-NpVOvNM5kPRN92UoiTe": "DAACECFEFDBBCBECCBBABADED",
            "-NrvCegRD76rYG-XsLoJ": "DACBBCACEEDCACDBAADACBDAA",
            "-NsYFspxJEiTiDW5hjsK": "BAECDBECBCDACACEBCDCABDCA",
            "-NsZT88aMZPMQg-is5AE": "CBCCCDDECADACABCEECABDCCA",
            "-NsJcmposNNkMqxQOpW-": "BABDABDDCABEDBCCCDACCBCCA",
            "-Nq2bedGQROrqUVWYy0s": "CABDAEECBABACADBCAAAADCBD",
            "-Nu-qsnPbBaEBagrevvV": "DBDBEDCEEABABCABEDACBBCEC",
            "-NtqIK4ame820uCcEAL0": "EBCCBBBDCBAEACCBEEDABBCCE",
            "-NsJziCuug-NS9grwFjW": "DAFCCDCEBABDBDCCABBABACDD",
            "-NrzK06W8HlJCHgnqfsc": "DADCEDCEEABBCABCEBBAADDCD",
            "-Npze7iSYGXgq6mSvsxw": "DAECDEEECBBDAEECBEAADBDED",
            "-Nr1Q5rL4YdJ4ePbJWUP": "DACBDDACBDBABBECDBBABBDED",
            "-Npe6HG4lBqyBdqxx2Hh": "DADCDDEDECBBCBECBEBACCDDD",
            "-NsPZD8J76PbJfhN8VHy": "DCBCDEDCBBBABBCCDBBADADCD",
            "-NsjGmbHx0mg3dng_t-U": "DEAAACCCCCBDBDECABBAABCED",
            "-NrGp70JkzBpzsDCJilf": "BCCCDCDECBDCAADCDBCBDACDD",
            "-NsZSxQiOeUmSXBcjA8s": "DCABAACEBABEBCCDBBCAABDEA",
            "-NqnKXr8J1VzCE_0HnhN": "DCBCECDEBDBADBBCDACDCBDCD",
            "-NpLmgvmQ2irtNwS5IJl": "ACCBBCEECEBADDECAACABDDCD",
            "-NsntqldomSiAanR3tyG": "DADCEEABCAAACACBDDBABADCD",
            "-NpK4z0EODLTECxOJzoO": "DAACEDDEBABCCABCCBBABBDDD",
            "-NpR3HewtcJrMyfKoFxb": "DCDBADDDDEBCAACAAADACCCED",
            "-NsYLDxPypTPNiNOpVr_": "AADDDDCDCABACCDCCBBEEBEEE",
            "-NsEdBrDl21dtr1r2Oz_": "ECBAAEEBEEBCACECCDBBCCCBD",
            "-Nu0i3HZRkPgnWV3cTgj": "DDCCEDECBEDAACCCDBBBACDDD",
            "-NsPWcJjjVBcyGfew-_Y": "DCEDEADDCDBBDACCDABAAACCD",
            "-NsON4LSXfwibuQexwuu": "CEDDACACEABCCBCCEBCACACDA",
            "-Ntrd0Y8mZRrCXZWWCHf": "DBACBDEDEBCAAAACADABDACDA",
            "-NsV4Fj2QZqlNkwjWlhk": "DCDCDCCEDCADAAECADBAACDED",
            "-NsPMHwLvw51_vlTjU_v": "DABDDBCCECBCABCCBCADBACDD",
            "-NsPwDSC5zlU6xjLQkTE": "DAADECBECABDACBCABBAABDCD",
            "-NsKAfHzETpb6A29qUmE": "DCBDBECCCBBDAACBCEBACDCCD",
            "-Nsj8T2H5O2C_GGlnPT2": "DDBDCEACEAABCDBCBBBAABCDD",
            "-NpMM8woPq89N863HG2J": "DADCDABEDCBBAAECCBBAADDCD",
            "-Ntg2qm_mumKdE_HFBUZ": "ACBCCCDCDCBDBCCCAABABACCD",
            "-NsUAwL_5b_t4wJxmDHc": "DAADEECBBCBABDEEABDAABCCD",
            "-NpLsC8PSX2eIIISaP_v": "DAEDEBDCDABBEDECBBBCCADCD",
            "-NpLrGzNXMZeuOGz2tPV": "DBBCADCEEEBAAAEABCDCAACCD",
            "-NrzcUk2he0PVutmByQ6": "DEACEEDEBCBAABACCBBAADCCA",
            "-NpKJdnzEgtaWvMl2DUk": "DCBADCECDEAACDECEBBDDDFCA",
            "-NsIt72LxuiPGaK_ntrE": "DABDCACEEABABDEDAEBABACCA",
            "-NsIr2GBBkNl-K3J5PRS": "DACCCBACEECABAADCBBACADED",
            "-Nr_kRZEcbAXTP2qepsC": "DECCEDDBCBBAAABBEBBACBDCA",
            "-NrHNzZdQBcJE0qU7sI0": "DBDCBEEEDBBACAECADAAAADCD",
            "-Nrp-sxfD-5tC-L2Denn": "CCDCBAEECBBDAACCAACABAACD",
            "-NrClBYuWqNTs7y0jVYZ": "DCCDDEABCCBAADBCBCBBBACCD",
            "-NsKvR29sb7FxbqIpMH3": "ADEBCEAECBBAADBCDBCEDBCAA",
            "-NstwRhrlCZA0gA4o9Yu": "DCCCBCDBBDADEDBBEDBABCDAD",
            "-NrHzk1lVw-T3PooAfC_": "DDACDDBCEBBCCBECCBBAACCCD",
            "-NrI-b5fciAL2RlZpONZ": "DBABDBAEBCBCACECEBBCADCCD",
            "-NpVlanEWAtxkpH5sARU": "DECCBDDECBDBAABCCBBCCECDA",
            "-NsPshdnWzfiK_9cZlpE": "DCDDACBECABCDABCABBAABCCD",
            "-NsQ2P5CTw_EuPUn_z6F": "DCBDBCCBECDAABACCBBACADCD",
            "-NrbN5k7HtBLP23iJDcD": "DCECAEACDCBCCAAEDBCBABCAD",
            "-NqE5jQHQHQxYKHb2M9p": "DBDCCEEEDDBCADACCDBACCCCD",
            "-Nse2jIhaahBr-im3CiU": "DEEBEEDABEBBBDCCEDDCCBCAA",
            "-NqE7-yQQg8aavh-zZww": "DADDEECABDBAADBDEBBACBCDD",
            "-NrCT0dZcy_gtJ9HPYAN": "DADDCCDCEABEDAECBACAABDEC",
            "-NpPlHLIswZwfrP8Cncd": "DAEDBADECBDCBDECBDBABADCD",
            "-NrCq2JtQP0c0nEUtpml": "DADCEDCEDABBAAECDBCAADAED",
            "-Nq8DV6xcofQ6iln-mcc": "DCACEBCDCABBABECABBADBCCD",
            "-NsOv0lA47iH_NTQ0tKR": "DAEDEAEEEBDBCCEBBAAAADCCD",
            "-NsUYi1FaTFQvJgYArgI": "DDBEACBDEABACCACCDCAEACCA",
            "-NrgM6h9cr6spEw7eS5B": "DCCCDAECCDBDCDCDCDCABCCCD",
            "-NrQnDd70P_BVo86jErN": "DCDDEEEDDABCADECABCACDCCD",
            "-NrvdepIVDJ7xe6seuaz": "ACBBADCCCEDACABCEADABBCAD",
            "-NpKogmSQ_6EaYDUFE_G": "BCCCEADEBCBAADFCFFFFFFFFD",
            "-NtrdurxUGybEtxs8xu1": "DBACBDCDEADDACCCCDBABDDAD",
            "-NpL6_sR5yVYw7p56Bjf": "DEBCEEACCABACACCAABACACCD",
            "-NpLePgVaXoc3lsrefZB": "DEDDACAABDDAAACABCBADBDEE",
            "-NpLfYIQ36bNFwrkmHGU": "DEBBEEBCDBBCCDBCEBBCCCCDB",
            "-NpK82n1WVl5mU86q-On": "DACCBADEBDBECCCEDABAABDAD",
            "-NpKAVj0bJtl26MknJkO": "DABDEDEEDBBACACBADCDABCCD",
            "-NsKlHZ3o7akVjlMRRtZ": "DAECECBEEABBBBECAABACDDEA",
            "-Npudr4IJ6rm8aFtOCr9": "DCBACCAEBBBAEBBCDDAABACDD",
            "-NstB9_RicRx8b45kQJ0": "DABBCCABAABACAECABAACBCCB",
            "-NpR6_yv7RBXgqRQWZR6": "DAACACDCDEBBDCCCBDBABECCD",
            "-NsV2bAezhJV0rO2hql_": "DCECAECCCEBAABACCBBABCCED",
            "-NtwropMYHk2yPJ5cSf4": "DABCCABCBEBDEABCCBBDDADDA",
            "-NpKQ8sovULP_aJMG8Op": "DCDCBCAEBBBDABECBBBABDDCD",
            "-NsKbolG--v1AonP_HPs": "DBBBCEBCDEBCACBCCBBAADCAD",
            "-NsYnHPDg01FSg3VFF-m": "DCADECBBEEBAACDCEDBABCCCE",
            "-NsPyBoStF4gKTfI1SrM": "DADBBDDEBCBBCDBBEBBABDDDB",
            "-NsYAYF4cLoFBb1-KetB": "DBACBDDEDCBAABACBDBACDDDD",
            "-NsPbxx1GJp1MNYBhnoA": "DACBDBCEACBCEADCECBADDCCD",
            "-Ns9uC6HkBj2sH3NGGxB": "DCCBDCAEEECACCECEBBAAADCD",
            "-NrLER7dwg0Z4l_PcWY0": "DBCCCABECEAEABCDBBCAADCCA"
        }
    },
    "Unicamp_00001": {
        "Gabarito": {
            "1": {"Resposta": "B", "Disciplina": "Filosofia", "Conteudo": ["Filosofia"]},
            "2": {"Resposta": "D", "Disciplina": "Filosofia", "Conteudo": ["Filosofia"]},
            "3": {"Resposta": "C", "Disciplina": "Filosofia", "Conteudo": ["Filosofia"]},
            "4": {"Resposta": "C", "Disciplina": "Sociologia", "Conteudo": ["Sociologia de Marx", "Teorias de Estado"]},
            "5": {"Resposta": "D", "Disciplina": "Sociologia", "Conteudo": ["Sociologia de Durkheim"]},
            "6": {"Resposta": "A", "Disciplina": "Sociologia", "Conteudo": ["Introdução à Sociologia"]},
            "7": {"Resposta": "D", "Disciplina": "Geografia", "Conteudo": ["Forças Internas e Externas da Terra", "Dinâmica da Terra"]},
            "8": {"Resposta": "A", "Disciplina": "Geografia", "Conteudo": ["Litosfera", "Placas Tectônicas"]},
            "9": {"Resposta": "C", "Disciplina": "Geografia", "Conteudo": ["Referências Geográficas", "Localização no Espaço", "Latitude e Longitude"]},
            "10": {"Resposta": "B", "Disciplina": "Geografia", "Conteudo": ["Geopolítica", "População", "IDH"]},
            "11": {"Resposta": "C", "Disciplina": "Geografia", "Conteudo": ["Concentração de Renda", "Desenvolvimento Econômico", "Indice GINI"]},
            "12": {"Resposta": "D", "Disciplina": "Geografia", "Conteudo": ["Estrutura Política Brasileira", "Sistema Bicameral"]},
            "13": {"Resposta": "C", "Disciplina": "Geografia", "Conteudo": ["Organização do Estado", "Constituição", "Estrutura Política"]},
            "14": {"Resposta": "A", "Disciplina": "Biologia", "Conteudo": ["Características dos Seres Vivos"]},
            "15": {"Resposta": "C", "Disciplina": "Biologia", "Conteudo": ["Citoplasma", "Organelas"]},
            "16": {"Resposta": "B", "Disciplina": "Biologia", "Conteudo": ["Vírus"]},
            "17": {"Resposta": "C", "Disciplina": "Biologia", "Conteudo": ["Composição Química da Célula", "Características dos Seres Vivos"]},
            "18": {"Resposta": "A", "Disciplina": "Biologia", "Conteudo": ["Origem da Vida"]},
            "19": {"Resposta": "C", "Disciplina": "Biologia", "Conteudo": ["Composição Química da Célula"]},
            "20": {"Resposta": "B", "Disciplina": "Biologia", "Conteudo": ["Vírus"]},
            "21": {"Resposta": "D", "Disciplina": "História", "Conteudo": ["Ditadura Militar Brasileira"]},
            "22": {"Resposta": "C", "Disciplina": "História", "Conteudo": ["Período Colonial", "Produção de Riqueza", "Escravismo"]},
            "23": {"Resposta": "B", "Disciplina": "História", "Conteudo": ["América Pré-Colombiana", "Antiguidade Oriental"]},
            "24": {"Resposta": "C", "Disciplina": "História", "Conteudo": ["História da Arte"]},
            "25": {"Resposta": "C", "Disciplina": "História", "Conteudo": ["Período Imperial", "Escravismo"]},
            "26": {"Resposta": "C", "Disciplina": "História", "Conteudo": ["Grécia"]},
            "27": {"Resposta": "C", "Disciplina": "História", "Conteudo": ["Cronologia"]},
            "28": {"Resposta": "A", "Disciplina": "Português", "Conteudo": ["Interpretação de Texto", "Gêneros Textuais"]},
            "29": {"Resposta": "C", "Disciplina": "Português", "Conteudo": ["Variações Linguísticas"]},
            "30": {"Resposta": "B", "Disciplina": "Português", "Conteudo": ["Interpretação de Texto", "Formação de Palavras"]},
            "31": {"Resposta": "B", "Disciplina": "Português", "Conteudo": ["Interpretação de Texto", "Formação de Palavras"]},
            "32": {"Resposta": "B", "Disciplina": "Português", "Conteudo": ["Formação de Palavras"]},
            "33": {"Resposta": "C", "Disciplina": "Português", "Conteudo": ["Formação de Palavras"]},
            "34": {"Resposta": "B", "Disciplina": "Português", "Conteudo": ["Formação de Palavras"]},
            "35": {"Resposta": "B", "Disciplina": "Literatura", "Conteudo": ["Literatura"]},
            "36": {"Resposta": "C", "Disciplina": "Literatura", "Conteudo": ["Literatura"]},
            "37": {"Resposta": "D", "Disciplina": "Literatura", "Conteudo": ["Literatura"]},
            "38": {"Resposta": "B", "Disciplina": "Literatura", "Conteudo": ["Literatura"]},
            "39": {"Resposta": "C", "Disciplina": "Literatura", "Conteudo": ["Literatura"]},
            "40": {"Resposta": "B", "Disciplina": "Matemática", "Conteudo": ["Aritmética", "Porcentagem", "Matemática Financeira"]},
            "41": {"Resposta": "C", "Disciplina": "Matemática", "Conteudo": ["Conjuntos Numéricos", "Inequações", "Gráficos"]},
            "42": {"Resposta": "D", "Disciplina": "Matemática", "Conteudo": ["Lógica Matemática", "Interpretação"]},
            "43": {"Resposta": "C", "Disciplina": "Matemática", "Conteudo": ["Conjuntos Numéricos", "Operação entre Conjuntos"]},
            "44": {"Resposta": "B", "Disciplina": "Matemática", "Conteudo": ["Teoria das Funções", "Equação", "Progressão Aritmética"]},
            "45": {"Resposta": "B", "Disciplina": "Matemática", "Conteudo": ["Interpretação", "Porcentagem", "Aritmética", "Frações"]},
            "46": {"Resposta": "C", "Disciplina": "Matemática", "Conteudo": ["Geometria Plana", "Noções de Geometria", "Teorema de Pitágoras"]},
            "47": {"Resposta": "B", "Disciplina": "Matemática", "Conteudo": ["Geometria Plana", "Conceitos de Geometria", "Aritmética"]},
            "48": {"Resposta": "A", "Disciplina": "Matemática", "Conteudo": ["Progressão"]},
            "49": {"Resposta": "C", "Disciplina": "Matemática", "Conteudo": ["Lógica", "Tabela", "Aritmética", "Equação", "Inequação"]},
            "50": {"Resposta": "A", "Disciplina": "Matemática", "Conteudo": ["Geometria", "Teorema dos Senos", "Pitágoras", "Conceitos de Geometria Plana"]},
            "51": {"Resposta": "B", "Disciplina": "Matemática", "Conteudo": ["Geometria Plana", "Setor Circular"]},
            "52": {"Resposta": "B", "Disciplina": "Física", "Conteudo": ["Sistema Internacional de Unidades (SI)", "Fundamentos de Cinemática"]},
            "53": {"Resposta": "D", "Disciplina": "Física", "Conteudo": ["Física"]},
            "54": {"Resposta": "A", "Disciplina": "Física", "Conteudo": ["Física"]},
            "55": {"Resposta": "A", "Disciplina": "Física", "Conteudo": ["Física"]},
            "56": {"Resposta": "C", "Disciplina": "Física", "Conteudo": ["Física"]},
            "57": {"Resposta": "B", "Disciplina": "Física", "Conteudo": ["Física"]},
            "58": {"Resposta": "B", "Disciplina": "Física", "Conteudo": ["Física"]},
            "59": {"Resposta": "D", "Disciplina": "Química", "Conteudo": ["Química"]},
            "60": {"Resposta": "A", "Disciplina": "Química", "Conteudo": ["Química"]},
            "61": {"Resposta": "C", "Disciplina": "Química", "Conteudo": ["Química"]},
            "62": {"Resposta": "D", "Disciplina": "Química", "Conteudo": ["Química"]},
            "63": {"Resposta": "B", "Disciplina": "Química", "Conteudo": ["Química"]},
            "64": {"Resposta": "C", "Disciplina": "Química", "Conteudo": ["Química"]},
            "65": {"Resposta": "B", "Disciplina": "Química", "Conteudo": ["Química"]},
            "66": {"Resposta": "C", "Disciplina": "Inglês", "Conteudo": ["Inglês"]},
            "67": {"Resposta": "C", "Disciplina": "Inglês", "Conteudo": ["Inglês"]},
            "68": {"Resposta": "C", "Disciplina": "Inglês", "Conteudo": ["Inglês"]},
            "69": {"Resposta": "B", "Disciplina": "Inglês", "Conteudo": ["Inglês"]},
            "70": {"Resposta": "D", "Disciplina": "Inglês", "Conteudo": ["Inglês"]},
            "71": {"Resposta": "C", "Disciplina": "Inglês", "Conteudo": ["Inglês"]},
            "72": {"Resposta": "C", "Disciplina": "Inglês", "Conteudo": ["Inglês"]},
        },
        "Gabarito_Alunos": {
            "-Nr7ChLzI5WL-DXmRmvB": "DABCDADABCCACDCBCADBDCBCCACAACBBBBDCBBCDADDBBCCBDCABDABCADAABDBDBADCBDAD",
            "-NrgM6h9cr6spEw7eS5B": "BAABDADDDCCADDDDCDABBBBCACBCDABBCABADBCBADCCBBDADDAABADCADCAAABBBAABABAB",
            "-NrzcUk2he0PVutmByQ6": "BDCCDACADBCACACDBAABBCBAACCADBDBDAACDBBDAACCABCBBAAABAABCCBACABABACCCACC",
            "-NsIt72LxuiPGaK_ntrE": "BDCCCACBAAACDCAAADBDCCBCDAAADBBBBABCDDCCAAABACCACBBBCCDCCCCAADCDCDBDBDCD",
            "-NsPwDSC5zlU6xjLQkTE": "BDCDDADDAACACADBCBABDCACACCABBDBCABCDDCCBACBCBBADDBCADADBACADDBACDBCBDAB",
            "-NpLfYIQ36bNFwrkmHGU": "BBCDCAAADAAABDBAABBBDCACCCDCCBBBCACCBBACBDBCAACABCABCCADCCAADBBBACACBBDA",
            "-NpLrGzNXMZeuOGz2tPV": "BCCBDADACCCAABBCDCDBBBDCBCBCCDBDBBCADBBBCDDDBBCBCBDCADCCABDBACDCDBBBDCBA",
            "-Ntg2qm_mumKdE_HFBUZ": "ADDAADADCAACACCCABDBBBCADDBCBDCACACADBCBBDCDABBADBBCBCBBBBAACBBCBDDADCAB",
            "-NpKogmSQ_6EaYDUFE_G": "BCABBCDAAAAAACDBCADBCCCDDBBBBBDCCACADBADBDCBADCACBBBDAADCADABDBABBACDCAC",
            "-NsIr2GBBkNl-K3J5PRS": "BDCCDADDBCCACDDAAADADCBCBCAAACBCBABCDBCBADCDCACDCABDCCBBCABAABBDBDCABBAB",
            "-NpR6_yv7RBXgqRQWZR6": "BDDCDDDBCDCCADBBABABFCBCCABCCBCBAAACDBCCBACDAACABBDCCABCDDBACABABCCCBDCC",
            "-NrI-b5fciAL2RlZpONZ": "ADBBBCABDAACACCDBCDADBAAACDCBCBBCABABBABAACCABACBCBBDACDBACCDABDDBDABDCD",
            "-NpR-d_vVz_JvBJst93E": "BDBCDAAAABCCDBCBCAABDBBCACCAABBABBBCAADCCAACADCBCDBBBCACBAAADCBCBCCCCAAC",
            "-NrHzk1lVw-T3PooAfC_": "BBCCDADDACCACDABCDBBDCBACACACBBBCBBCDBCCBDCACADDFFDBCADDBADAAABDBCCDDDAC",
            "-NsYAYF4cLoFBb1-KetB": "ACCCDADBCACCDDCACBCDACDACABCDBCBAAAADBDCBAABBBBAABBCDACDBADADCBABBCDBBDC",
            "-NrQnDd70P_BVo86jErN": "BDCDDADADBAACCBBCACDBBDCCABCBBBBDABCDBCACCCDFCCBBDABCAABCDABCCBDBCCCBABC",
            "-NpKQ8sovULP_aJMG8Op": "BDBCDADBDCCCDCBBCBCBBCBCCCCABBDBBABCDDCDCACBABCACCCCBACCACDACCCCBCCCBDAD",
            "-NstB9_RicRx8b45kQJ0": "BBCCDADABDAADDADBCDBBCBDBCCBACBCBBACABCDBACBCABABBAAACDABBDCDABACBAAACCA",
            "-NsOv0lA47iH_NTQ0tKR": "BDCCDADBAACACADACBABDCBCCCBCBBBBCADCBBCDADCBCBCACBCBAABCADDADABDBCCDBDCC",
            "-Nsj8T2H5O2C_GGlnPT2": "BACCDADABBBAADABCBCDBBBACCCDABBADBBCDBCBADCBADCADCACDCABBCCACDBDBCACBBDC",
            "-NrHNzZdQBcJE0qU7sI0": "ADCDCADDBCCACDABCAADDCBAACCCDBDCCABCDBCDADCDACCACDBBCAADBCDADABABCCCBAAC",
            "-NpPaHEgFS-MtM6eoWrD": "BABDDADADACACBDACBBBBABBACCCCABBBADBCDCCBDCCAACACDBCCACCBDDAAABABCBCCAAC",
            "-Nq8DV6xcofQ6iln-mcc": "BCCCDADADCCBCDCBCAABDBBCCBCBCBACCCBCDBCBBDCCBADAAABABDCAADBADABABACCBBDC",
            "-NpMM8woPq89N863HG2J": "BDCCDDDAACAACCDBCBDBCBBCCBCADBBABABADACCDACCCAABCBBDCCADDCDAAABDBACCBBAC",
            "-NrCq2JtQP0c0nEUtpml": "BDCADADBABCACCABCDABBDBCACCCAABCDBCABDACAACBABDACCBBBAADCCCADABABDCADCAC",
            "-NrbN5k7HtBLP23iJDcD": "BACCCDABAADCBCACBCBABCDBCABCBABCACCDDCCBCACDBACABCADDABCCCDAAABDBCCCBDAD",
            "-Nu0i3HZRkPgnWV3cTgj": "BBCCDDDADACCCCAACAABDCBCBCBADBDAAABCDBCBADABCBCBCCDCDCCACCCDADAADBAABCBC",
            "-Npze7iSYGXgq6mSvsxw": "BAACBADAAACBCDBACCCBDCDCCCAABBDBAAAACBCCCACBCACBDDBBBACCACAADDBDBBBCBDBD",
            "-NrvdepIVDJ7xe6seuaz": "DCCCDAAAACCDACBBACCBDBBCDCBDCDDABDCBBBCAAAACDBBBBBBBCCACBCDABDBABACADDCA",
            "-NpK4z0EODLTECxOJzoO": "BCCCDADAABADDBCBCABBBDBCCCCCBBBCAABABBCDCDCCABDADCDBCAACADDACDBABCCCBDBD",
            "-NsZSxQiOeUmSXBcjA8s": "BDCCCAAADCAABDABCABBCCBDBBBABBBAAAACCBCCAABCABBADDCCCCBBCBCAABBCBBCDBDAA",
            "-NpLmgvmQ2irtNwS5IJl": "BDDCCADACACCDBCCCCCDCCBCCCBADBBAABCBDBCBAAACDBADBCCCDADCDACACABCDBCCBDAD",
            "-NtqIK4ame820uCcEAL0": "CADBBBAADACADABDDCDDCDCDCCBDBCCACBAABBBCCDAADCBABDCCAADACCAACBCCBDDABABB",
            "-NpR3HewtcJrMyfKoFxb": "BABCDABCCDDCCDABBCCDACBDACBDDBCADBBCCDCDCDCBCBCBCBBBCDCACBCADBBADACABAAA",
            "-NsJziCuug-NS9grwFjW": "BDCCCADDBACCDDBACBBBDCBDCCAADBDBAABACDCBAAADCBCBCCBBBCABBCCADABDBDBCADBC",
            "-NsPZD8J76PbJfhN8VHy": "BBACDADDCCABBBBBCACBCCBAACCCABBBBADABBCCBDADBADADDCBDBBBBCDACDBDBCCCBDAD",
            "-NrGp70JkzBpzsDCJilf": "BDCCDADBDACCABABACABBCBDDCACCBCBBCBCABCDBDBDCADACCBDBABCACDADDBABAACBBAC",
            "-NsJcmposNNkMqxQOpW-": "BDBCCADADACCADDDDADCBCBCAAACCBBACABCDDCBBDCCBDCCCBAADADDDBCACDBABADCBACD",
            "-NsPWcJjjVBcyGfew-_Y": "BBBDDADBBACACBCCDADBCCBBCCDBBCDACABDADDBADCCCDCDDBBBCACBDADABDBABCCCBDAD",
            "-NsOww_fKbENEzWwvkIO": "BDCCCADADDCABDBACADBDDBBCABACBBADBDABDCCAACAAACACADBADCCBDCCCDBCBDACDDAD",
            "-Npe6HG4lBqyBdqxx2Hh": "BDCCDADDBAAACDBDCACBDBBCCCCACBBABACCDDACCDCCADCABDBBDAABBCBABDBABACCADAC",
            "-NsjGmbHx0mg3dng_t-U": "BDCCDADBAAFACBDACACBACAAABCCCBBABABCCBCDDADAACCCCDBACAACBBCAAABADDABBBCB",
            "-NsYHhgYGB9jpXeaHI8_": "BABCDDDBACCADADACDDBBCDACABABDDACABACBBAADCBABCBABCDCAACDBBACBBDBACCBBAC",
            "-NpKGYe49ixF4BXth9dG": "BDCCDADABDCAADABCCABBCAABCCACBBCAABCDBCDADADCBCCDDBCDBDCBACAADBABBCABDBC",
            "-Ns9eSl96YVtghzvsAwD": "BBCCDBACDDCAACABDBDBABDCBCADDBCADCACBDABDDACCDBDCACACCACBADACABDBACDDACC",
            "-NsTs2dq4GFs_VpMQOij": "BDCADABAADCACCBDBABBBDCCBCDACACACACCDDCDAACDCCCAADCCCCACADBACABDBCCDBDAC",
            "-Ns8r6VDAMD6IP95qS-s": "BDCDDADBBCAACDAACACBDCDCCCDAACBDCACCDDACBACDCCBADCBCCAABBCDCCDBABCCCAAAC",
            "-NsnzcJn11H_CFbx-EmB": "BDCCDADACCCBCDABAAADDDBCACCCABDBBDBCDDCACACCAACDCCDBCABCACDACABDBACAAAAC",
            "-NsUCHyhCYuW4frHavih": "ADCCDAACDCACCDBBCACBDBDCCCCDCBBBAACCBBCCBDAAACDCCBADCCBDCBDACDCDBCCCBACD",
            "-NrLER7dwg0Z4l_PcWY0": "BDBCDCAABCAADDBAACDBCDACBCACACDABBBADDCDADCCCBBBABBAACADBCCACCBFFDCDDAAC",
            "-NsT3untPBVbLsxZMVHS": "ADBCDADADBCADDDBCCADDCAAABBABBDDBBBBBBCDADCCABCBABBACDCDBCAACCBDAACABABB",
            "-NswaxcU1dM9Mi3FKZHK": "FCCADADCCBDACDABACABCCFDABACCBDACAACDBCBDACABACBDBBCCAACBCACAABBFDBCDAAA",
            "-Nt1TjePJxmLayK2xFmX": "BDCCCADADAAABBBCDADBDCDCDCDDABBABBCABDCCDDABCCDABBBDCACDBAAACCBDBCDCBADC",
            "-Nqn4BS-IcscyfSJHbWx": "BBADBADAACBADDBACAABBCDCCDCCABDBCBAADDCCADCABBCADCDCDABCDACACDBABBCBDACC",
            "-NrBuWfRVnTXIqUkVD7j": "BDCCDADADBABCBACCABBDCBCACCACBDBCABADBCCBAACABCBBBDCCDACDABACABABDCADACC",
            "-NsYLDxPypTPNiNOpVr_": "BDCCDCDCDACCBDCCCCABBCDAACBDDBBBCABCDBCCCCBCBBCDBDCDBCDCDDCDBBCBCBCBBCDB",
            "-Nq9I4ofd6J2336fdHX6": "ACBCDADCDCCACBCCACCDBCBCAAADBBBBDCCCCDCCAACABBCDCCCCCACCCAAAAABDABAABABC",
            "-Nq2bedGQROrqUVWYy0s": "BBCCDADBDACACCABCBADDCADCCCBABBDBADADBCCADACABDABCADDADCACCACABBBACDBADB",
            "-NsY6FAnM58MtuZbY5hu": "BDCCDDAAAACCDDABAACBCAADABBDDABBBBDCCBCDBDCBABCADCDBBCAADADACBBDBADDACAA",
            "-NpM60kZr97ETBSjT3em": "BDCCDADABCABCDCBCABBCDBCACCACBBBCAACDBCCDDACABDACCABDAACDDDADABDBDCCBDAC",
            "-NsTzS33TAhT_zgyRkN8": "BDACDAAAACACACABBABDDCBCCAADCDDABBCABDBDBACDCDBDDBCCBCDCACAACBBABDCAACAA",
            "-NsYEMn7hWYI35kzAJxc": "BDCCDADABCAADDDBAACDBCBCACCACBBCCABCDDCDAACBAACADBBBAABCADBACCBDAACCBADC",
            "-NrzK06W8HlJCHgnqfsc": "BDCDDADAAAACACDBCABBBCBCAACACBBBCBCCDBCABDABCBBBBBCCCAAADCDACABBBCCCBDAC",
            "-NsEdBrDl21dtr1r2Oz_": "DFCACACCACCCBCDABADBDCADBABDABAFBBBCBDBCBACCBCCBCADBDDADCABBCBBDDCBACAAB",
            "-NrL3RnCv9VE9jcT4qpz": "BCCADAABACCCBDDBCCDDCBBCDADDBBDABBCCDACDBDCACABDDBBCBCDAAACBABBDDDABBAAB",
            "-NsZ2TUAS2FTuOMqw89H": "BDCCDADACAABCCBBCACBDCBCACCCCBBBCABCDBCCFDAFBCFFFFFBDAACBDDACDBDBCCCBDCC",
            "-NsPyBoStF4gKTfI1SrM": "BDCCDABCDBCADDBBBBADDDDACCCBDBDBCABCDBCBCACCDBCACDBBCDBDBCDACADABCDCBBAC",
            "-NruBjdIiUYUWW5ABguL": "DDACDABDCDBCCDBBAADAACCDCBBABCCDDAABADCBCADCACABCACCADCCBDADDABDBDDACABD",
            "-NsON4LSXfwibuQexwuu": "CDCCDAAADACCDDCAACDBDBDACACCACBCBACCBBACCACDCCBADDCCACBCDCBADCBCCACBBAAB",
            "-NuUE9Kfiwa2geR8o3AL": "BDCDDADACABADDCBCABBBDBACCCCDBBBAABCDBCDCBBBCCCCCCCBCABCCCDACDBDBCCCBBAC",
            "-NsZ7IEQYxO9-cGpPG8f": "BCDCDABABACBCDCDCADBDCDCACBAADBBBBABCBCAAADDCBCDCABCBDCDBADACCBABADBBDAC",
            "-Ns8MzOoubwwCWpPoAlD": "DACCDADAAACCAABBCBABBCBDAADCABACCBBFCBDBBDCDCDABBDABCABCBDBAADBABBCABBCA",
            "-NsPbxx1GJp1MNYBhnoA": "BDBDCDAADDCCADDBBDABCBACAACDCBDBBDACDCCACACCBBABCDCBADCDAABADBBACDDBCBBC",
            "-NpVlanEWAtxkpH5sARU": "BBCFDDCAACCADBDCBAABDCCCBDDADBBABCCACBACADCABACDDDBBCDDDBCDCBABADDABBDAC",
            "-NsKAfHzETpb6A29qUmE": "DBABDABCDAAACCBBBCAADCBCBDBBBCDADABACDCDCACBAABCCCDBCAACCBBADDDBBABDBACA",
            "-NsOLr_C6dmsd-aAblHP": "BDCDDACCAACACBCCDBCDDCBCBCAACABACBDCBDDCAACDABCABCABCAACCCABADBACBBCABAC",
            "-NrpsYAA3XldX1MQDHpT": "BDCACDDADACBBABBCAAADCDBCBCDADDACBADBBCDCDCDCABCBDBBBDACDCBAACBADCADACAB",
            "-NpeiYH7rSht16NQwg06": "BDCCDADABACADCABCACBBCACACAADBBABACCAADCBDDCBABCDBDCDAACCDCBBDBDDDCDBBAC",
            "-NrerG7lApyhE37b23Bq": "BDBCDDDAAAACDDBCAACDCBADABDDCBDBBAAACDCBBDCBABCADCDBBCAAAADABABDAACDAAAA",
            "-NsKbolG--v1AonP_HPs": "BCACBBCBDCCBBADDDAAACBAAABADCBDCBBDACDBBCDABBCCABACAACCBCABCBCCCBADABCDB",
            "-Nrq6lwAfkLPXeOQxPfz": "BCCCDAAABDAADDCBCCDBBCBCDCCACBDBBABCDACDBACBCACCCDCBCACABBCADCBDDCCDBDCC",
            "-NsmHzt00jL-Jlmah01W": "BDCCDADAACCCDDBBCCBBADBACACDBBDBAABCBBCBBDCBAADABCBDAADCACBACCBDCACDCAAD",
            "-NsYFspxJEiTiDW5hjsK": "BDCCAADDDCCABDCBCBCBDCBCACDCCABBDABABDCBDACBCBDBDCDBBCCADDCACBBDCACDBCAA",
            "-NsUTGl1YqoJw9odOF1Q": "BDCCDADADCACCDDBCABDDCBCACCAABDBCBBCDBCBBDCBACDABCDBCADCACDACABABCCCBBBC",
            "-Ns9uC6HkBj2sH3NGGxB": "BDCDDADAACCCABDACBCBBCBBCACABBBACACCDBCBADCCCBAAABBBABDCAAAAADBDACCCBBBC"
        }
    },
    "USP_00001": {
        "Gabarito": {
            "1": {"Resposta" :"C", "Disciplina": "Biologia", "Conteudo": [""]},
            "2": {"Resposta" :"E", "Disciplina": "Biologia", "Conteudo": [""]},
            "3": {"Resposta" :"C", "Disciplina": "Biologia", "Conteudo": [""]},
            "4": {"Resposta" :"B", "Disciplina": "Biologia", "Conteudo": [""]},
            "5": {"Resposta" :"E", "Disciplina": "Biologia", "Conteudo": [""]},
            "6": {"Resposta" :"A", "Disciplina": "Biologia", "Conteudo": [""]},
            "7": {"Resposta" :"C", "Disciplina": "Biologia", "Conteudo": [""]},
            "8": {"Resposta" :"C", "Disciplina": "Biologia", "Conteudo": [""]},
            "9": {"Resposta" :"A", "Disciplina": "Biologia", "Conteudo": [""]},
            "10": {"Resposta" :"A", "Disciplina": "Biologia", "Conteudo": [""]},
            "11": {"Resposta" :"E", "Disciplina": "Biologia", "Conteudo": [""]},
            "12": {"Resposta" :"B", "Disciplina": "Biologia", "Conteudo": [""]},
            "13": {"Resposta" :"B", "Disciplina": "Química", "Conteudo": [""]},
            "14": {"Resposta" :"E", "Disciplina": "Química", "Conteudo": [""]},
            "15": {"Resposta" :"C", "Disciplina": "Química", "Conteudo": [""]},
            "16": {"Resposta" :"B", "Disciplina": "Química", "Conteudo": [""]},
            "17": {"Resposta" :"E", "Disciplina": "Química", "Conteudo": [""]},
            "18": {"Resposta" :"E", "Disciplina": "Química", "Conteudo": [""]},
            "19": {"Resposta" :"B", "Disciplina": "Química", "Conteudo": [""]},
            "20": {"Resposta" :"E", "Disciplina": "Química", "Conteudo": [""]},
            "21": {"Resposta" :"B", "Disciplina": "Química", "Conteudo": [""]},
            "22": {"Resposta" :"C", "Disciplina": "Química", "Conteudo": [""]},
            "23": {"Resposta" :"A", "Disciplina": "Matemática", "Conteudo": [""]},
            "24": {"Resposta" :"D", "Disciplina": "Matemática", "Conteudo": [""]},
            "25": {"Resposta" :"C", "Disciplina": "Matemática", "Conteudo": [""]},
            "26": {"Resposta" :"C", "Disciplina": "Matemática", "Conteudo": [""]},
            "27": {"Resposta" :"D", "Disciplina": "Matemática", "Conteudo": [""]},
            "28": {"Resposta" :"C", "Disciplina": "Matemática", "Conteudo": [""]},
            "29": {"Resposta" :"D", "Disciplina": "Matemática", "Conteudo": [""]},
            "30": {"Resposta" :"D", "Disciplina": "Matemática", "Conteudo": [""]},
            "31": {"Resposta" :"E", "Disciplina": "Matemática", "Conteudo": [""]},
            "32": {"Resposta" :"B", "Disciplina": "Matemática", "Conteudo": [""]},
            "33": {"Resposta" :"E", "Disciplina": "Matemática", "Conteudo": [""]},
            "34": {"Resposta" :"A", "Disciplina": "Matemática", "Conteudo": [""]},
            "35": {"Resposta" :"E", "Disciplina": "Matemática", "Conteudo": [""]},
            "36": {"Resposta" :"D", "Disciplina": "Matemática", "Conteudo": [""]},
            "37": {"Resposta" :"C", "Disciplina": "Matemática", "Conteudo": [""]},
            "38": {"Resposta" :"B", "Disciplina": "Matemática", "Conteudo": [""]},
            "39": {"Resposta" :"C", "Disciplina": "Física", "Conteudo": [""]},
            "40": {"Resposta" :"C", "Disciplina": "Física", "Conteudo": [""]},
            "41": {"Resposta" :"D", "Disciplina": "Física", "Conteudo": [""]},
            "42": {"Resposta" :"D", "Disciplina": "Física", "Conteudo": [""]},
            "43": {"Resposta" :"E", "Disciplina": "Física", "Conteudo": [""]},
            "44": {"Resposta" :"D", "Disciplina": "Física", "Conteudo": [""]},
            "45": {"Resposta" :"A", "Disciplina": "Física", "Conteudo": [""]},
            "46": {"Resposta" :"B", "Disciplina": "Física", "Conteudo": [""]},
            "47": {"Resposta" :"B", "Disciplina": "Física", "Conteudo": [""]},
            "48": {"Resposta" :"A", "Disciplina": "Física", "Conteudo": [""]},
            "49": {"Resposta" :"B", "Disciplina": "Geografia", "Conteudo": [""]},
            "50": {"Resposta" :"A", "Disciplina": "Geografia", "Conteudo": [""]},
            "51": {"Resposta" :"D", "Disciplina": "Geografia", "Conteudo": [""]},
            "52": {"Resposta" :"C", "Disciplina": "Geografia", "Conteudo": [""]},
            "53": {"Resposta" :"D", "Disciplina": "Geografia", "Conteudo": [""]},
            "54": {"Resposta" :"D", "Disciplina": "Geografia", "Conteudo": [""]},
            "55": {"Resposta" :"D", "Disciplina": "Geografia", "Conteudo": [""]},
            "56": {"Resposta" :"D", "Disciplina": "Geografia", "Conteudo": [""]},
            "57": {"Resposta" :"B", "Disciplina": "Geografia", "Conteudo": [""]},
            "58": {"Resposta" :"E", "Disciplina": "Geografia", "Conteudo": [""]},
            "59": {"Resposta" :"B", "Disciplina": "Sociologia", "Conteudo": [""]},
            "60": {"Resposta" :"B", "Disciplina": "Sociologia", "Conteudo": [""]},
            "61": {"Resposta" :"D", "Disciplina": "Sociologia", "Conteudo": [""]},
            "62": {"Resposta" :"D", "Disciplina": "Filosofia", "Conteudo": [""]},
            "63": {"Resposta" :"C", "Disciplina": "Filosofia", "Conteudo": [""]},
            "64": {"Resposta" :"B", "Disciplina": "Filosofia", "Conteudo": [""]},
            "65": {"Resposta" :"A", "Disciplina": "História", "Conteudo": [""]},
            "66": {"Resposta" :"B", "Disciplina": "História", "Conteudo": [""]},
            "67": {"Resposta" :"C", "Disciplina": "História", "Conteudo": [""]},
            "68": {"Resposta" :"C", "Disciplina": "História", "Conteudo": [""]},
            "69": {"Resposta" :"D", "Disciplina": "História", "Conteudo": [""]},
            "70": {"Resposta" :"E", "Disciplina": "História", "Conteudo": [""]},
            "71": {"Resposta" :"B", "Disciplina": "História", "Conteudo": [""]},
            "72": {"Resposta" :"B", "Disciplina": "História", "Conteudo": [""]},
            "73": {"Resposta" :"D", "Disciplina": "História", "Conteudo": [""]},
            "74": {"Resposta" :"D", "Disciplina": "História", "Conteudo": [""]},
            "75": {"Resposta" :"D", "Disciplina": "História", "Conteudo": [""]},
            "76": {"Resposta" :"B", "Disciplina": "História", "Conteudo": [""]},
            "77": {"Resposta" :"A", "Disciplina": "Português", "Conteudo": [""]},
            "78": {"Resposta" :"A", "Disciplina": "Português", "Conteudo": [""]},
            "79": {"Resposta" :"A", "Disciplina": "Português", "Conteudo": [""]},
            "80": {"Resposta" :"C", "Disciplina": "Português", "Conteudo": [""]},
            "81": {"Resposta" :"A", "Disciplina": "Português", "Conteudo": [""]},
            "82": {"Resposta" :"D", "Disciplina": "Português", "Conteudo": [""]},
            "83": {"Resposta" :"A", "Disciplina": "Português", "Conteudo": [""]},
            "84": {"Resposta" :"A", "Disciplina": "Português", "Conteudo": [""]},
            "85": {"Resposta" :"E", "Disciplina": "Português", "Conteudo": [""]},
            "86": {"Resposta" :"E", "Disciplina": "Português", "Conteudo": [""]},
            "87": {"Resposta" :"A", "Disciplina": "Português", "Conteudo": [""]},
            "89": {"Resposta" :"A", "Disciplina": "Português", "Conteudo": [""]},
            "90": {"Resposta" :"E", "Disciplina": "Português", "Conteudo": [""]} 
        },
    }
}
