simulados = {
    "Colmeias_Inicial": {
        "Nome": "Colmeias_Inicial",
        "Banca": "Extensão",
        "Questões": {
            "Total": 25,
            "Matemática": 5,
            "Português": 5,
            "Literatura": 0,
            "Química": 3,
            "Física": 3,
            "Biologia": 3,
            "História": 3,
            "Geografia": 3,
            "Inglês": 0,
            "Sociologia": 0,
            "Filosofia": 0
        },
        "Gabarito": {
            "1": {"Resposta": "D", "Disciplina": "Português", "Conteudo": ["Funções da Linguagem", "Morfologia"]},
            "2": {"Resposta": "A", "Disciplina": "Português", "Conteudo": ["Morfologia", "Concordância Verbal"]},
            "3": {"Resposta": "A", "Disciplina": "Português", "Conteudo": ["Funções da Linguagem", "Variação Linguística"]},
            "4": {"Resposta": "C", "Disciplina": "Português", "Conteudo": ["Figuras de Linguagem", "Morfologia", "Verbos"]},
            "5": {"Resposta": "E", "Disciplina": "Português", "Conteudo": ["Morfologia", "Substantivo, Adjetivo, Numeral e Artigo"]},
            "6": {"Resposta": "D", "Disciplina": "Física", "Conteudo": ["Movimento uniforme", "Matemática Básica", "Porcentagem"]},
            "7": {"Resposta": "B", "Disciplina": "Física", "Conteudo": ["Ondulatória", "Movimento Uniforme"]},
            "8": {"Resposta": "E", "Disciplina": "Física", "Conteudo": ["Eletricidade", "Gráficos"]},
            "9": {"Resposta": "E", "Disciplina": "Matemática", "Conteudo": ["Geometria Espacial", "Volume"]},
            "10": {"Resposta": "A", "Disciplina": "Matemática", "Conteudo": ["Medidas de Centralidade e Dispersão", "Tabela"]},
            "11": {"Resposta": "B", "Disciplina": "Matemática", "Conteudo": ["Matemática Básica", "Adição e Subtração", "Potenciação", "Radiciação"]},
            "12": {"Resposta": "B", "Disciplina": "Matemática", "Conteudo": ["Porcentagem", "Matemática Financeira"]},
            "13": {"Resposta": "C", "Disciplina": "Matemática", "Conteudo": ["Função do 1º Grau", "Gráficos", "Tabela"]},
            "14": {"Resposta": "B", "Disciplina": "Geografia", "Conteudo": ["Conceitos em Geografia e Introdução à Demografia", "Migrações"]},
            "15": {"Resposta": "E", "Disciplina": "Geografia", "Conteudo": ["Industrialização Brasileira"]},
            "16": {"Resposta": "C", "Disciplina": "Geografia", "Conteudo": ["Energia"]},
            "17": {"Resposta": "C", "Disciplina": "História", "Conteudo": ["Governo Vargas"]},
            "18": {"Resposta": "B", "Disciplina": "História", "Conteudo": ["Idade Moderna"]},
            "19": {"Resposta": "B", "Disciplina": "História", "Conteudo": ["Segunda Guerra Mundial", "Autoritarismo"]},
            "20": {"Resposta": "A", "Disciplina": "Química", "Conteudo": ["Química Orgânica"]},
            "21": {"Resposta": "A", "Disciplina": "Química", "Conteudo": ["Química Orgânica", "Classificação e Hibridização do Carbono", "Classificação de Cadeias Carbônicas"]},
            "22": {"Resposta": "D", "Disciplina": "Química", "Conteudo": ["Equilíbrio Iônico"]},
            "23": {"Resposta": "D", "Disciplina": "Biologia", "Conteudo": ["Biociclos e Biomas", "Ecologia"]},
            "24": {"Resposta": "C", "Disciplina": "Biologia", "Conteudo": ["Saúde"]},
            "25": {"Resposta": "D", "Disciplina": "Biologia", "Conteudo": ["Citologia"]}
        },
    },
    "Unicamp_00001": {
        "Nome": "Unicamp_00001",
        "Banca": "COMVEST",
        "Questões": {
            "Total": 72,
            "Matemática": 12,
            "Português": 7,
            "Literatura": 5,
            "Química": 7,
            "Física": 7,
            "Biologia": 7,
            "História": 7,
            "Geografia": 7,
            "Inglês": 7,
            "Sociologia": 3,
            "Filosofia": 3
        },
        "Gabarito": {
            "1": {"Resposta": "B", "Disciplina": "Filosofia", "Conteudo": ["Filosofia"]},
            "2": {"Resposta": "D", "Disciplina": "Filosofia", "Conteudo": ["Filosofia"]},
            "3": {"Resposta": "C", "Disciplina": "Filosofia", "Conteudo": ["Filosofia"]},
            "4": {"Resposta": "C", "Disciplina": "Sociologia", "Conteudo": ["Sociologia de Marx", "Teorias de Estado"]},
            "5": {"Resposta": "D", "Disciplina": "Sociologia", "Conteudo": ["Sociologia de Durkheim"]},
            "6": {"Resposta": "A", "Disciplina": "Sociologia", "Conteudo": ["Introdução à Sociologia"]},
            "7": {"Resposta": "D", "Disciplina": "Geografia", "Conteudo": ["Forças Internas e Externas da Terra", "Dinâmica da Terra"]},
            "8": {"Resposta": "A", "Disciplina": "Geografia", "Conteudo": ["Litosfera", "Placas Tectônicas"]},
            "9": {"Resposta": "C", "Disciplina": "Geografia", "Conteudo": ["Referências Geográficas", "Localização no Espaço", "Latitude e Longitude"]},
            "10": {"Resposta": "B", "Disciplina": "Geografia", "Conteudo": ["Geopolítica", "População", "IDH"]},
            "11": {"Resposta": "C", "Disciplina": "Geografia", "Conteudo": ["Concentração de Renda", "Desenvolvimento Econômico", "Indice GINI"]},
            "12": {"Resposta": "D", "Disciplina": "Geografia", "Conteudo": ["Estrutura Política Brasileira", "Sistema Bicameral"]},
            "13": {"Resposta": "C", "Disciplina": "Geografia", "Conteudo": ["Organização do Estado", "Constituição", "Estrutura Política"]},
            "14": {"Resposta": "A", "Disciplina": "Biologia", "Conteudo": ["Características dos Seres Vivos"]},
            "15": {"Resposta": "C", "Disciplina": "Biologia", "Conteudo": ["Citoplasma", "Organelas"]},
            "16": {"Resposta": "B", "Disciplina": "Biologia", "Conteudo": ["Vírus"]},
            "17": {"Resposta": "C", "Disciplina": "Biologia", "Conteudo": ["Composição Química da Célula", "Características dos Seres Vivos"]},
            "18": {"Resposta": "A", "Disciplina": "Biologia", "Conteudo": ["Origem da Vida"]},
            "19": {"Resposta": "C", "Disciplina": "Biologia", "Conteudo": ["Composição Química da Célula"]},
            "20": {"Resposta": "B", "Disciplina": "Biologia", "Conteudo": ["Vírus"]},
            "21": {"Resposta": "D", "Disciplina": "História", "Conteudo": ["Ditadura Militar Brasileira"]},
            "22": {"Resposta": "C", "Disciplina": "História", "Conteudo": ["Período Colonial", "Produção de Riqueza", "Escravismo"]},
            "23": {"Resposta": "B", "Disciplina": "História", "Conteudo": ["América Pré-Colombiana", "Antiguidade Oriental"]},
            "24": {"Resposta": "C", "Disciplina": "História", "Conteudo": ["História da Arte"]},
            "25": {"Resposta": "C", "Disciplina": "História", "Conteudo": ["Período Imperial", "Escravismo"]},
            "26": {"Resposta": "C", "Disciplina": "História", "Conteudo": ["Grécia"]},
            "27": {"Resposta": "C", "Disciplina": "História", "Conteudo": ["Cronologia"]},
            "28": {"Resposta": "A", "Disciplina": "Português", "Conteudo": ["Interpretação de Texto", "Gêneros Textuais"]},
            "29": {"Resposta": "C", "Disciplina": "Português", "Conteudo": ["Variações Linguísticas"]},
            "30": {"Resposta": "B", "Disciplina": "Português", "Conteudo": ["Interpretação de Texto", "Formação de Palavras"]},
            "31": {"Resposta": "B", "Disciplina": "Português", "Conteudo": ["Interpretação de Texto", "Formação de Palavras"]},
            "32": {"Resposta": "B", "Disciplina": "Português", "Conteudo": ["Formação de Palavras"]},
            "33": {"Resposta": "C", "Disciplina": "Português", "Conteudo": ["Formação de Palavras"]},
            "34": {"Resposta": "B", "Disciplina": "Português", "Conteudo": ["Formação de Palavras"]},
            "35": {"Resposta": "B", "Disciplina": "Literatura", "Conteudo": ["Literatura"]},
            "36": {"Resposta": "C", "Disciplina": "Literatura", "Conteudo": ["Literatura"]},
            "37": {"Resposta": "D", "Disciplina": "Literatura", "Conteudo": ["Literatura"]},
            "38": {"Resposta": "B", "Disciplina": "Literatura", "Conteudo": ["Literatura"]},
            "39": {"Resposta": "C", "Disciplina": "Literatura", "Conteudo": ["Literatura"]},
            "40": {"Resposta": "B", "Disciplina": "Matemática", "Conteudo": ["Aritmética", "Porcentagem", "Matemática Financeira"]},
            "41": {"Resposta": "C", "Disciplina": "Matemática", "Conteudo": ["Conjuntos Numéricos", "Inequações", "Gráficos"]},
            "42": {"Resposta": "D", "Disciplina": "Matemática", "Conteudo": ["Lógica Matemática", "Interpretação"]},
            "43": {"Resposta": "C", "Disciplina": "Matemática", "Conteudo": ["Conjuntos Numéricos", "Operação entre Conjuntos"]},
            "44": {"Resposta": "B", "Disciplina": "Matemática", "Conteudo": ["Teoria das Funções", "Equação", "Progressão Aritmética"]},
            "45": {"Resposta": "B", "Disciplina": "Matemática", "Conteudo": ["Interpretação", "Porcentagem", "Aritmética", "Frações"]},
            "46": {"Resposta": "C", "Disciplina": "Matemática", "Conteudo": ["Geometria Plana", "Noções de Geometria", "Teorema de Pitágoras"]},
            "47": {"Resposta": "B", "Disciplina": "Matemática", "Conteudo": ["Geometria Plana", "Conceitos de Geometria", "Aritmética"]},
            "48": {"Resposta": "A", "Disciplina": "Matemática", "Conteudo": ["Progressão"]},
            "49": {"Resposta": "C", "Disciplina": "Matemática", "Conteudo": ["Lógica", "Tabela", "Aritmética", "Equação", "Inequação"]},
            "50": {"Resposta": "A", "Disciplina": "Matemática", "Conteudo": ["Geometria", "Teorema dos Senos", "Pitágoras", "Conceitos de Geometria Plana"]},
            "51": {"Resposta": "B", "Disciplina": "Matemática", "Conteudo": ["Geometria Plana", "Setor Circular"]},
            "52": {"Resposta": "B", "Disciplina": "Física", "Conteudo": ["Sistema Internacional de Unidades (SI)", "Fundamentos de Cinemática"]},
            "53": {"Resposta": "D", "Disciplina": "Física", "Conteudo": ["Física"]},
            "54": {"Resposta": "A", "Disciplina": "Física", "Conteudo": ["Física"]},
            "55": {"Resposta": "A", "Disciplina": "Física", "Conteudo": ["Física"]},
            "56": {"Resposta": "C", "Disciplina": "Física", "Conteudo": ["Física"]},
            "57": {"Resposta": "B", "Disciplina": "Física", "Conteudo": ["Física"]},
            "58": {"Resposta": "B", "Disciplina": "Física", "Conteudo": ["Física"]},
            "59": {"Resposta": "D", "Disciplina": "Química", "Conteudo": ["Química"]},
            "60": {"Resposta": "A", "Disciplina": "Química", "Conteudo": ["Química"]},
            "61": {"Resposta": "C", "Disciplina": "Química", "Conteudo": ["Química"]},
            "62": {"Resposta": "D", "Disciplina": "Química", "Conteudo": ["Química"]},
            "63": {"Resposta": "B", "Disciplina": "Química", "Conteudo": ["Química"]},
            "64": {"Resposta": "C", "Disciplina": "Química", "Conteudo": ["Química"]},
            "65": {"Resposta": "B", "Disciplina": "Química", "Conteudo": ["Química"]},
            "66": {"Resposta": "C", "Disciplina": "Inglês", "Conteudo": ["Inglês"]},
            "67": {"Resposta": "C", "Disciplina": "Inglês", "Conteudo": ["Inglês"]},
            "68": {"Resposta": "C", "Disciplina": "Inglês", "Conteudo": ["Inglês"]},
            "69": {"Resposta": "B", "Disciplina": "Inglês", "Conteudo": ["Inglês"]},
            "70": {"Resposta": "D", "Disciplina": "Inglês", "Conteudo": ["Inglês"]},
            "71": {"Resposta": "C", "Disciplina": "Inglês", "Conteudo": ["Inglês"]},
            "72": {"Resposta": "C", "Disciplina": "Inglês", "Conteudo": ["Inglês"]},
        },
    },
    "USP_00001": {
        "Nome": "USP_00001",
        "Banca": "FUVEST",
        "Questões": {
            "Total": 90,
            "Matemática": 16,
            "Português": 14,
            "Literatura": 0,
            "Química": 10,
            "Física": 10,
            "Biologia": 12,
            "História": 12,
            "Geografia": 10,
            "Inglês": 0,
            "Sociologia": 3,
            "Filosofia": 3
            },
        "Gabarito": {
            "1": {"Resposta" :"C", "Disciplina": "Biologia", "Conteudo": [""]},
            "2": {"Resposta" :"E", "Disciplina": "Biologia", "Conteudo": [""]},
            "3": {"Resposta" :"C", "Disciplina": "Biologia", "Conteudo": [""]},
            "4": {"Resposta" :"B", "Disciplina": "Biologia", "Conteudo": [""]},
            "5": {"Resposta" :"E", "Disciplina": "Biologia", "Conteudo": [""]},
            "6": {"Resposta" :"A", "Disciplina": "Biologia", "Conteudo": [""]},
            "7": {"Resposta" :"C", "Disciplina": "Biologia", "Conteudo": [""]},
            "8": {"Resposta" :"C", "Disciplina": "Biologia", "Conteudo": [""]},
            "9": {"Resposta" :"A", "Disciplina": "Biologia", "Conteudo": [""]},
            "10": {"Resposta" :"A", "Disciplina": "Biologia", "Conteudo": [""]},
            "11": {"Resposta" :"E", "Disciplina": "Biologia", "Conteudo": [""]},
            "12": {"Resposta" :"B", "Disciplina": "Biologia", "Conteudo": [""]},
            "13": {"Resposta" :"B", "Disciplina": "Química", "Conteudo": [""]},
            "14": {"Resposta" :"E", "Disciplina": "Química", "Conteudo": [""]},
            "15": {"Resposta" :"C", "Disciplina": "Química", "Conteudo": [""]},
            "16": {"Resposta" :"B", "Disciplina": "Química", "Conteudo": [""]},
            "17": {"Resposta" :"E", "Disciplina": "Química", "Conteudo": [""]},
            "18": {"Resposta" :"E", "Disciplina": "Química", "Conteudo": [""]},
            "19": {"Resposta" :"B", "Disciplina": "Química", "Conteudo": [""]},
            "20": {"Resposta" :"E", "Disciplina": "Química", "Conteudo": [""]},
            "21": {"Resposta" :"B", "Disciplina": "Química", "Conteudo": [""]},
            "22": {"Resposta" :"C", "Disciplina": "Química", "Conteudo": [""]},
            "23": {"Resposta" :"A", "Disciplina": "Matemática", "Conteudo": [""]},
            "24": {"Resposta" :"D", "Disciplina": "Matemática", "Conteudo": [""]},
            "25": {"Resposta" :"C", "Disciplina": "Matemática", "Conteudo": [""]},
            "26": {"Resposta" :"C", "Disciplina": "Matemática", "Conteudo": [""]},
            "27": {"Resposta" :"D", "Disciplina": "Matemática", "Conteudo": [""]},
            "28": {"Resposta" :"C", "Disciplina": "Matemática", "Conteudo": [""]},
            "29": {"Resposta" :"D", "Disciplina": "Matemática", "Conteudo": [""]},
            "30": {"Resposta" :"D", "Disciplina": "Matemática", "Conteudo": [""]},
            "31": {"Resposta" :"E", "Disciplina": "Matemática", "Conteudo": [""]},
            "32": {"Resposta" :"B", "Disciplina": "Matemática", "Conteudo": [""]},
            "33": {"Resposta" :"E", "Disciplina": "Matemática", "Conteudo": [""]},
            "34": {"Resposta" :"A", "Disciplina": "Matemática", "Conteudo": [""]},
            "35": {"Resposta" :"E", "Disciplina": "Matemática", "Conteudo": [""]},
            "36": {"Resposta" :"D", "Disciplina": "Matemática", "Conteudo": [""]},
            "37": {"Resposta" :"C", "Disciplina": "Matemática", "Conteudo": [""]},
            "38": {"Resposta" :"B", "Disciplina": "Matemática", "Conteudo": [""]},
            "39": {"Resposta" :"C", "Disciplina": "Física", "Conteudo": [""]},
            "40": {"Resposta" :"C", "Disciplina": "Física", "Conteudo": [""]},
            "41": {"Resposta" :"D", "Disciplina": "Física", "Conteudo": [""]},
            "42": {"Resposta" :"D", "Disciplina": "Física", "Conteudo": [""]},
            "43": {"Resposta" :"E", "Disciplina": "Física", "Conteudo": [""]},
            "44": {"Resposta" :"D", "Disciplina": "Física", "Conteudo": [""]},
            "45": {"Resposta" :"A", "Disciplina": "Física", "Conteudo": [""]},
            "46": {"Resposta" :"B", "Disciplina": "Física", "Conteudo": [""]},
            "47": {"Resposta" :"B", "Disciplina": "Física", "Conteudo": [""]},
            "48": {"Resposta" :"A", "Disciplina": "Física", "Conteudo": [""]},
            "49": {"Resposta" :"B", "Disciplina": "Geografia", "Conteudo": [""]},
            "50": {"Resposta" :"A", "Disciplina": "Geografia", "Conteudo": [""]},
            "51": {"Resposta" :"D", "Disciplina": "Geografia", "Conteudo": [""]},
            "52": {"Resposta" :"C", "Disciplina": "Geografia", "Conteudo": [""]},
            "53": {"Resposta" :"D", "Disciplina": "Geografia", "Conteudo": [""]},
            "54": {"Resposta" :"D", "Disciplina": "Geografia", "Conteudo": [""]},
            "55": {"Resposta" :"D", "Disciplina": "Geografia", "Conteudo": [""]},
            "56": {"Resposta" :"D", "Disciplina": "Geografia", "Conteudo": [""]},
            "57": {"Resposta" :"B", "Disciplina": "Geografia", "Conteudo": [""]},
            "58": {"Resposta" :"E", "Disciplina": "Geografia", "Conteudo": [""]},
            "59": {"Resposta" :"B", "Disciplina": "Sociologia", "Conteudo": [""]},
            "60": {"Resposta" :"B", "Disciplina": "Sociologia", "Conteudo": [""]},
            "61": {"Resposta" :"D", "Disciplina": "Sociologia", "Conteudo": [""]},
            "62": {"Resposta" :"D", "Disciplina": "Filosofia", "Conteudo": [""]},
            "63": {"Resposta" :"C", "Disciplina": "Filosofia", "Conteudo": [""]},
            "64": {"Resposta" :"B", "Disciplina": "Filosofia", "Conteudo": [""]},
            "65": {"Resposta" :"A", "Disciplina": "História", "Conteudo": [""]},
            "66": {"Resposta" :"B", "Disciplina": "História", "Conteudo": [""]},
            "67": {"Resposta" :"C", "Disciplina": "História", "Conteudo": [""]},
            "68": {"Resposta" :"C", "Disciplina": "História", "Conteudo": [""]},
            "69": {"Resposta" :"D", "Disciplina": "História", "Conteudo": [""]},
            "70": {"Resposta" :"E", "Disciplina": "História", "Conteudo": [""]},
            "71": {"Resposta" :"B", "Disciplina": "História", "Conteudo": [""]},
            "72": {"Resposta" :"B", "Disciplina": "História", "Conteudo": [""]},
            "73": {"Resposta" :"D", "Disciplina": "História", "Conteudo": [""]},
            "74": {"Resposta" :"D", "Disciplina": "História", "Conteudo": [""]},
            "75": {"Resposta" :"D", "Disciplina": "História", "Conteudo": [""]},
            "76": {"Resposta" :"B", "Disciplina": "História", "Conteudo": [""]},
            "77": {"Resposta" :"A", "Disciplina": "Português", "Conteudo": [""]},
            "78": {"Resposta" :"A", "Disciplina": "Português", "Conteudo": [""]},
            "79": {"Resposta" :"A", "Disciplina": "Português", "Conteudo": [""]},
            "80": {"Resposta" :"C", "Disciplina": "Português", "Conteudo": [""]},
            "81": {"Resposta" :"A", "Disciplina": "Português", "Conteudo": [""]},
            "82": {"Resposta" :"D", "Disciplina": "Português", "Conteudo": [""]},
            "83": {"Resposta" :"A", "Disciplina": "Português", "Conteudo": [""]},
            "84": {"Resposta" :"A", "Disciplina": "Português", "Conteudo": [""]},
            "85": {"Resposta" :"E", "Disciplina": "Português", "Conteudo": [""]},
            "86": {"Resposta" :"E", "Disciplina": "Português", "Conteudo": [""]},
            "87": {"Resposta" :"A", "Disciplina": "Português", "Conteudo": [""]},
            "89": {"Resposta" :"A", "Disciplina": "Português", "Conteudo": [""]},
            "90": {"Resposta" :"E", "Disciplina": "Português", "Conteudo": [""]} 
        },
    }
}
